// Cursed Reaper Scythe - skills, combo, cooldowns and VFX timing.
// Animation-synced data (blade trails, anchor points) is generated by tools/reaper/build.py
// into reaper_data.js from the same rig that produced the animations.
import { world, system, MolangVariableMap, EntityDamageCause } from "@minecraft/server";
import { TRAILS, ANCHORS, GLOW, CLIP_TICKS } from "./reaper_data.js";

const ITEM = "idex:cursed_reaper_scythe";
const CTRL = "idex_reaper";
const STOP = `!q.is_item_name_any('slot.weapon.mainhand', 0, '${ITEM}')`;
const FX_FAMILY = "reaper_fx";

const SKILLS = [
    { id: "crimson_crescent", name: "§cCrimson Crescent", cd: 3, cast: castCrescent },
    { id: "reapers_chain", name: "§4Reaper's Chain", cd: 7, cast: castChain },
    { id: "phantom_scythe", name: "§8Phantom Scythe", cd: 15, cast: castPhantom },
    { id: "blood_moon", name: "§cBlood Moon", cd: 25, cast: castBloodMoon },
    { id: "abyssal_reap", name: "§5Abyssal Reap", cd: 18, cast: castAbyssalReap },
    { id: "eclipse_requiem", name: "§4§lEclipse Requiem", cd: 60, cast: castEclipseRequiem },
];

const LORE = [
    "§r§7Cursed • Shadow • Crescent • Crimson",
    "§r§fClick §7- combo (3 hits)",
    "§r§fUse §7- cast selected skill",
    "§r§fSneak + Use §7- next skill",
    ...SKILLS.map((s) => `§r${s.name} §7(CD ${s.cd}s)`),
];

// ------------------------------------------------------------------ state
const states = new Map();
function S(player) {
    let s = states.get(player.id);
    if (!s) {
        s = {
            sel: 0, cds: {}, busyUntil: 0, combo: 0, lastSwing: -99, nextSwing: 0,
            holding: false, lastHold: 0, lastUse: -99, bloodMoonUntil: 0, phantom: null,
        };
        states.set(player.id, s);
    }
    return s;
}
world.afterEvents.playerLeave.subscribe((ev) => {
    const s = states.get(ev.playerId);
    if (s?.phantom?.entity) safe(() => s.phantom.entity.remove());
    states.delete(ev.playerId);
});

// ------------------------------------------------------------------ helpers
const now = () => system.currentTick;
function safe(fn) {
    try {
        return fn();
    } catch (e) {
        return undefined;
    }
}
function after(ticks, fn) {
    system.runTimeout(() => safe(fn), Math.max(0, Math.round(ticks)));
}
function valid(e) {
    if (!e) return false;
    const v = e.isValid;
    return typeof v === "function" ? e.isValid() : !!v;
}
function cmd(e, c) {
    return safe(() => e.runCommand(c));
}
function holding(player) {
    return safe(() => player.getComponent("equippable").getEquipment("Mainhand")?.typeId === ITEM) ?? false;
}
function vars(o) {
    const m = new MolangVariableMap();
    for (const k in o) m.setFloat(`variable.${k}`, o[k]);
    return m;
}
function fx(dim, id, loc, v) {
    safe(() => dim.spawnParticle(`idex:${id}`, loc, v ? vars(v) : new MolangVariableMap()));
}
function sound(player, id, loc, pitch = 1, vol = 1) {
    const l = loc ?? player.location;
    cmd(player, `playsound ${id} @a[x=${l.x.toFixed(2)},y=${l.y.toFixed(2)},z=${l.z.toFixed(2)},r=40] ${l.x.toFixed(2)} ${l.y.toFixed(2)} ${l.z.toFixed(2)} ${vol} ${pitch}`);
}
function shake(player, loc, r, power, time) {
    const l = loc ?? player.location;
    cmd(player, `camerashake add @a[x=${l.x.toFixed(2)},y=${l.y.toFixed(2)},z=${l.z.toFixed(2)},r=${r}] ${power} ${time} positional`);
}
const add = (a, b) => ({ x: a.x + b.x, y: a.y + b.y, z: a.z + b.z });
const mul = (a, k) => ({ x: a.x * k, y: a.y * k, z: a.z * k });
const sub = (a, b) => ({ x: a.x - b.x, y: a.y - b.y, z: a.z - b.z });
const len = (a) => Math.hypot(a.x, a.y, a.z);
const norm = (a) => {
    const l = len(a) || 1;
    return { x: a.x / l, y: a.y / l, z: a.z / l };
};

/** Frame locked at cast time: animation data is in player-local blocks (x right, y up, z forward). */
function frame(player) {
    const yaw = (player.getRotation().y * Math.PI) / 180;
    const f = { x: -Math.sin(yaw), y: 0, z: Math.cos(yaw) };
    const r = { x: -Math.cos(yaw), y: 0, z: -Math.sin(yaw) };
    return { pos: { ...player.location }, yaw: player.getRotation().y, f, r, dim: player.dimension };
}
function local(fr, p) {
    return {
        x: fr.pos.x + fr.r.x * p[0] + fr.f.x * p[2],
        y: fr.pos.y + p[1],
        z: fr.pos.z + fr.r.z * p[0] + fr.f.z * p[2],
    };
}
function liveFrame(player, fr) {
    // follow the caster while keeping the cast facing
    return { ...fr, pos: { ...player.location } };
}

function enemies(player, center, radius, extra = {}) {
    return (
        safe(() =>
            player.dimension.getEntities({
                location: center,
                maxDistance: radius,
                excludeFamilies: [FX_FAMILY, "inanimate"],
                excludeTypes: ["minecraft:item", "minecraft:xp_orb", "minecraft:arrow", "minecraft:armor_stand"],
                ...extra,
            })
        ) ?? []
    ).filter((e) => e.id !== player.id && valid(e));
}
function hurt(player, e, dmg, kb) {
    safe(() => e.applyDamage(dmg, { cause: EntityDamageCause.entityAttack, damagingEntity: player }));
    if (kb) {
        const d = norm({ x: e.location.x - kb.from.x, y: 0, z: e.location.z - kb.from.z });
        safe(() => e.applyKnockback(d.x, d.z, kb.h, kb.v));
    }
}
function inFront(fr, e, range, cosMin) {
    const d = sub(e.location, fr.pos);
    const h = Math.hypot(d.x, d.z);
    if (h > range) return false;
    if (h < 1.2) return true;
    return (d.x * fr.f.x + d.z * fr.f.z) / h >= cosMin;
}

// ------------------------------------------------------------------ animation
function play(player, clip, busyTicks) {
    const s = S(player);
    cmd(player, `playanimation @s animation.idex.reaper.${clip} a 0.12 "${STOP}" ${CTRL}`);
    const ticks = CLIP_TICKS[clip] ?? 20;
    s.busyUntil = Math.max(s.busyUntil, now() + (busyTicks ?? ticks));
    s.animEnd = now() + ticks;
    const token = (s.animToken = (s.animToken ?? 0) + 1);
    after(ticks, () => {
        if (s.animToken === token && holding(player)) hold(player);
    });
}
function hold(player) {
    const s = S(player);
    s.lastHold = now();
    cmd(player, `playanimation @s animation.idex.reaper.hold a 0.2 "${STOP}" ${CTRL}`);
}

/** Red blade trail along the animated tip path (sampled per tick from the rig). */
function trail(player, fr, key, opts = {}) {
    const segs = TRAILS[key];
    if (!segs) return;
    const follow = opts.follow ?? true;
    for (const seg of segs) {
        seg.pts.forEach((p, i) => {
            after(seg.start + i, () => {
                if (!valid(player)) return;
                const f = follow ? liveFrame(player, fr) : fr;
                const tip = local(f, [p[0], p[1], p[2]]);
                const mid = local(f, [p[3], p[4], p[5]]);
                const prev = i > 0 ? seg.pts[i - 1] : p;
                const tip0 = local(f, [prev[0], prev[1], prev[2]]);
                const steps = Math.min(8, Math.max(2, Math.ceil(len(sub(tip, tip0)) / 0.18)));
                for (let k = 0; k < steps; k++) {
                    const u = k / steps;
                    const a = add(tip0, mul(sub(tip, tip0), u));
                    fx(fr.dim, "reaper_trail", a, { size: opts.size ?? 0.17, life: opts.life ?? 0.24 });
                    if (opts.ground) fx(fr.dim, "reaper_trail", { x: a.x, y: fr.pos.y + 0.06, z: a.z }, { size: 0.2, life: 1.1 });
                }
                // a fainter sheet between tip and blade middle
                for (let k = 1; k < 4; k++) {
                    fx(fr.dim, "reaper_trail", add(mid, mul(sub(tip, mid), k / 4)), { size: 0.1, life: 0.16 });
                }
                if (opts.smoke && i % 2 === 0) fx(fr.dim, "reaper_trail_dark", tip, { life: 0.5, size: 0.3 });
                if (S(player).bloodMoonUntil > now() && i % 2 === 0) {
                    fx(fr.dim, "reaper_mini_crescent", tip, { count: 1, radius: 0.1, size: 0.8 });
                }
            });
        });
    }
}

// ------------------------------------------------------------------ phantom companion
const MIMIC = {
    attack1: "swing_left", attack2: "swing_up", attack3: "chop",
    crimson_crescent: "spin", chain_spin: "spin", abyssal_reap: "chop", eclipse_requiem: "spin",
};
function phantomSpot(player) {
    const fr = frame(player);
    return { loc: add(add(player.location, mul(fr.f, -1.5)), add(mul(fr.r, 1.1), { x: 0, y: 0.4, z: 0 })), yaw: fr.yaw };
}
function mimic(player, clip) {
    const s = S(player);
    const ph = s.phantom;
    if (!ph || !valid(ph.entity) || ph.leaving) return;
    const anim = MIMIC[clip];
    if (!anim) return;
    cmd(ph.entity, `playanimation @s animation.idex.phantom.${anim} a 0.1`);
    after(6, () => {
        const fr = frame(player);
        const c = add(ph.entity.location, add(mul(fr.f, 3.0), { x: 0, y: -0.5, z: 0 }));
        fx(player.dimension, "reaper_sparks", c, { count: 10 });
        fx(player.dimension, "reaper_trail_dark", c, { size: 0.9, life: 0.5 });
        for (const e of enemies(player, c, 3.4)) hurt(player, e, 6, { from: ph.entity.location, h: 0.6, v: 0.2 });
    });
}

// ------------------------------------------------------------------ blood moon extras on swings
function bloodMoonSwing(player, fr, clip) {
    const s = S(player);
    if (s.bloodMoonUntil <= now()) return;
    after(2, () => {
        const ai = safe(() => player.dimension.spawnEntity("idex:reaper_afterimage", player.location));
        if (!ai) return;
        safe(() => ai.teleport(add(player.location, mul(fr.f, -0.35)), { rotation: { x: 0, y: fr.yaw } }));
        cmd(ai, `playanimation @s animation.idex.reaper.${clip} a 0`);
        after(9, () => valid(ai) && ai.remove());
    });
    after(5, () => {
        for (let i = 0; i < 3; i++) {
            fx(fr.dim, "reaper_mini_crescent", local(liveFrame(player, fr), [i - 1, 1.2, 1.4]), { count: 1, radius: 0.2, size: 1 });
        }
    });
}

// ------------------------------------------------------------------ normal attack (3-hit combo)
function onMelee(player) {
    const s = S(player);
    const t = now();
    if (!holding(player) || t < s.busyUntil || t < s.nextSwing) return;
    s.combo = t - s.lastSwing < 18 ? (s.combo + 1) % 3 : 0;
    s.lastSwing = t;
    s.nextSwing = t + 9;
    const clip = ["attack1", "attack2", "attack3"][s.combo];
    const fr = frame(player);
    play(player, clip, 8);
    trail(player, fr, clip, { smoke: s.combo === 2 });
    sound(player, "item.trident.throw", null, 0.7 + 0.15 * s.combo, 0.8);
    const hitTick = [4, 4, 8][s.combo];
    after(hitTick, () => {
        const f = liveFrame(player, fr);
        const range = s.combo === 2 ? 4.2 : 3.8;
        for (const e of enemies(player, add(f.pos, { x: 0, y: 1, z: 0 }), range + 1)) {
            if (!inFront(f, e, range, s.combo === 2 ? -0.2 : 0.1)) continue;
            hurt(player, e, [5, 6, 9][s.combo], { from: f.pos, h: s.combo === 2 ? 0.9 : 0.45, v: s.combo === 2 ? 0.35 : 0.15 });
            fx(f.dim, "reaper_sparks", add(e.location, { x: 0, y: 1, z: 0 }), { count: 8 });
        }
        if (s.combo === 2) {
            const p = local(f, [0, 0.05, 2.2]);
            fx(f.dim, "reaper_ring", p, { size: 3.2, life: 0.45 });
            fx(f.dim, "reaper_smoke", p, { count: 6, radius: 0.6 });
            shake(player, p, 10, 0.25, 0.2);
            sound(player, "random.anvil_land", p, 0.6, 0.5);
        }
    });
    mimic(player, clip);
    bloodMoonSwing(player, fr, clip);
}
world.afterEvents.entityHitEntity.subscribe((ev) => {
    const p = ev.damagingEntity;
    if (p?.typeId === "minecraft:player") onMelee(p);
});
world.afterEvents.entityHitBlock.subscribe((ev) => {
    const p = ev.damagingEntity;
    if (p?.typeId === "minecraft:player") onMelee(p);
});

// ------------------------------------------------------------------ use: cast / cycle
world.afterEvents.itemUse.subscribe((ev) => {
    const player = ev.source;
    if (player?.typeId !== "minecraft:player" || ev.itemStack?.typeId !== ITEM) return;
    const s = S(player);
    const t = now();
    if (t - s.lastUse < 4) return;
    s.lastUse = t;
    if (player.isSneaking) {
        s.sel = (s.sel + 1) % SKILLS.length;
        sound(player, "random.click", null, 1.4, 0.6);
        hud(player, true);
        return;
    }
    const sk = SKILLS[s.sel];
    if (t < s.busyUntil) return;
    const ready = s.cds[sk.id] ?? 0;
    if (t < ready) {
        player.onScreenDisplay.setActionBar(`${sk.name} §7- cooldown §f${((ready - t) / 20).toFixed(1)}s`);
        return;
    }
    s.cds[sk.id] = t + sk.cd * 20;
    player.onScreenDisplay.setActionBar(`§l${sk.name}`);
    safe(() => sk.cast(player, s));
});

function hud(player, force) {
    const s = S(player);
    const t = now();
    const sk = SKILLS[s.sel];
    const ready = s.cds[sk.id] ?? 0;
    const state = t >= ready ? "§aREADY" : `§7${((ready - t) / 20).toFixed(1)}s`;
    let extra = "";
    if (s.bloodMoonUntil > t) extra += ` §c☾ ${((s.bloodMoonUntil - t) / 20).toFixed(0)}s`;
    if (s.phantom && valid(s.phantom.entity)) extra += ` §8✟ ${Math.max(0, (s.phantom.until - t) / 20).toFixed(0)}s`;
    if (force || t >= s.busyUntil) player.onScreenDisplay.setActionBar(`§8[§f${s.sel + 1}/${SKILLS.length}§8] ${sk.name} ${state}${extra}`);
}

// ------------------------------------------------------------------ 1. Crimson Crescent
function castCrescent(player) {
    const fr = frame(player);
    const view = player.getViewDirection();
    play(player, "crimson_crescent", 14);
    trail(player, fr, "crimson_crescent", { smoke: true, size: 0.2 });
    sound(player, "item.trident.riptide_1", null, 0.8, 0.8);
    after(8, () => {
        const f = liveFrame(player, fr);
        sound(player, "mob.wither.shoot", null, 0.6, 0.7);
        const dir = norm({ x: view.x, y: Math.max(-0.35, Math.min(0.35, view.y)), z: view.z });
        launchCrescent(player, add(local(f, [0, 1.15, 1.0]), mul(dir, 0.4)), dir, { size: 1, variant: 0, dmg: 12, range: 22, speed: 1.15, radius: 2.4 });
    });
    mimic(player, "crimson_crescent");
}

/** Crescent wave entity flown by script; deals damage once per target. */
function launchCrescent(player, origin, dir, o) {
    const dim = player.dimension;
    const e = safe(() => dim.spawnEntity("idex:reaper_crescent", origin));
    if (!e) return;
    safe(() => e.setProperty("idex:variant", o.variant));
    safe(() => e.setProperty("idex:size", o.size));
    const yaw = (Math.atan2(-dir.x, dir.z) * 180) / Math.PI;
    const hit = new Set();
    let travelled = 0;
    let pos = origin;
    const id = system.runInterval(() => {
        if (!valid(e) || travelled >= o.range) {
            system.clearRun(id);
            if (valid(e)) {
                fx(dim, "reaper_sparks", pos, { count: 18 * o.size, speed: 1.2 });
                fx(dim, "reaper_smoke", pos, { count: 8, radius: 0.8 * o.size, size: 0.8 });
                if (o.variant > 0) fx(dim, "reaper_rune", pos, { count: 10, radius: 2 * o.size, rise: 0.8 });
                safe(() => e.remove());
            }
            return;
        }
        const lift = o.lift ?? 0;
        pos = add(pos, add(mul(dir, o.speed), { x: 0, y: lift, z: 0 }));
        travelled += o.speed;
        safe(() => e.teleport(pos, { rotation: { x: 0, y: yaw } }));
        const back = add(pos, mul(dir, -0.8 * o.size));
        fx(dim, "reaper_sparks", back, { count: 4, radius: 0.5 * o.size, speed: 0.6 });
        fx(dim, "reaper_trail_dark", back, { life: 0.5, size: 0.45 * o.size });
        if (o.dmg > 0) {
            for (const t of enemies(player, pos, o.radius * Math.max(1, o.size) + 1)) {
                if (hit.has(t.id)) continue;
                const dy = t.location.y + 0.9 - pos.y;
                if (Math.abs(dy) > 1.8 * o.size) continue;
                hit.add(t.id);
                hurt(player, t, o.dmg, { from: sub(pos, mul(dir, 2)), h: 0.8, v: 0.25 });
                fx(dim, "reaper_sparks", add(t.location, { x: 0, y: 1, z: 0 }), { count: 12 });
            }
        }
    }, 1);
    return e;
}

// ------------------------------------------------------------------ 2. Reaper's Chain
function castChain(player) {
    const fr = frame(player);
    const view = player.getViewDirection();
    play(player, "reapers_chain", 26);
    trail(player, fr, "reapers_chain");
    sound(player, "item.trident.throw", null, 0.5, 0.8);
    after(7, () => {
        const f = liveFrame(player, fr);
        const circle = local(f, ANCHORS.chain_circle);
        fx(f.dim, "reaper_circle_face", circle, { size: 1.5, life: 0.9, spin: 260 });
        fx(f.dim, "reaper_sparks", circle, { count: 10, radius: 0.3 });
        sound(player, "mob.evocation_illager.cast_spell", circle, 1.2, 0.8);
        const target = safe(() => player.getEntitiesFromViewDirection({ maxDistance: 18 }))
            ?.map((h) => h.entity)
            .find((e) => valid(e) && e.id !== player.id && !e.typeId.startsWith("idex:reaper_") &&
                e.typeId !== "minecraft:item" && e.typeId !== "minecraft:xp_orb");
        const dir = norm(view);
        const maxLen = target ? len(sub(add(target.location, { x: 0, y: 1, z: 0 }), circle)) : 14;
        let head = 0;
        let caught = false;
        let jerk = 0;
        let yanked = false;
        let age = 0;
        const run = system.runInterval(() => {
            age++;
            if (!valid(player) || age > 40) return system.clearRun(run);
            const start = local(liveFrame(player, fr), ANCHORS.chain_circle);
            let end;
            if (caught && valid(target)) end = add(target.location, { x: 0, y: 1, z: 0 });
            else end = add(start, mul(dir, head));
            if (!caught) {
                head = Math.min(maxLen, head + 2.2);
                if (head >= maxLen) {
                    if (target && valid(target)) {
                        caught = true;
                        fx(f.dim, "reaper_ring", add(target.location, { x: 0, y: 0.1, z: 0 }), { size: 2.4, life: 0.7 });
                        fx(f.dim, "reaper_sparks", end, { count: 14 });
                        sound(player, "random.anvil_land", end, 1.6, 0.6);
                        hurt(player, target, 4);
                        jerk = 3;
                        after(Math.max(3, 15 - (7 + age)), () => {
                            if (!valid(target) || !valid(player)) return;
                            yanked = true;
                            const d = sub(player.location, target.location);
                            const dist = Math.hypot(d.x, d.z);
                            const n = norm({ x: d.x, y: 0, z: d.z });
                            safe(() => target.applyKnockback(n.x, n.z, Math.min(3.6, 0.32 * dist + 0.4), 0.38));
                            sound(player, "item.trident.return", player.location, 0.6, 1);
                            after(9, () => chainFinisher(player, fr, target));
                        });
                    } else if (age > 12) {
                        return system.clearRun(run);
                    }
                }
            } else if (yanked && age > 30) {
                return system.clearRun(run);
            }
            drawChain(f.dim, start, end, jerk > 0 ? jerk-- : 0, age);
        }, 1);
    });
}
function drawChain(dim, a, b, jerk, age) {
    const d = sub(b, a);
    const L = len(d);
    if (L < 0.2) return;
    const n = norm(d);
    const side = norm({ x: -n.z, y: 0, z: n.x });
    const count = Math.min(70, Math.floor(L / 0.26));
    for (let i = 0; i <= count; i++) {
        const u = i / Math.max(1, count);
        const wob = jerk ? Math.sin(u * Math.PI) * 0.35 * jerk : 0;
        const p = add(add(a, mul(d, u)), mul(side, wob));
        fx(dim, "reaper_chain_link", p, { dx: n.x, dy: n.y, dz: n.z, red: (i + (age >> 1)) % 2, life: 0.1 });
    }
    // runes travelling along the links
    const k = (age % 6) / 6;
    fx(dim, "reaper_rune", add(a, mul(d, k)), { size: 0.18, rise: 0.01 });
}
function chainFinisher(player, fr, target) {
    if (!valid(target) || len(sub(target.location, player.location)) > 4.2) return;
    const f = frame(player);
    play(player, "chain_spin", 14);
    trail(player, f, "chain_spin", { smoke: true });
    sound(player, "item.trident.riptide_2", null, 0.7, 0.9);
    mimic(player, "chain_spin");
    after(6, () => {
        const c = player.location;
        fx(f.dim, "reaper_void_wave", c, { size: 7, life: 0.7 });
        fx(f.dim, "reaper_ring", c, { size: 6, life: 0.6, cr: 0.25, cg: 0.0, cb: 0.05 });
        fx(f.dim, "reaper_smoke", add(c, { x: 0, y: 0.6, z: 0 }), { count: 10, radius: 1.8 });
        for (const e of enemies(player, c, 3.6)) hurt(player, e, 8, { from: c, h: 1.0, v: 0.3 });
        shake(player, c, 12, 0.2, 0.25);
    });
}

// ------------------------------------------------------------------ 3. Phantom Scythe
function castPhantom(player, s) {
    const fr = frame(player);
    play(player, "phantom_scythe", 30);
    sound(player, "mob.evocation_illager.prepare_summon", null, 0.7, 0.8);
    after(9, () => {
        const c = { ...player.location };
        fx(fr.dim, "reaper_circle", c, { size: 4.6, life: 2.4, spin: 35 });
        fx(fr.dim, "reaper_circle_ring_a", c, { size: 5.4, life: 2.4, spin: -55 });
        fx(fr.dim, "reaper_void_wave", c, { size: 4, life: 0.5 });
        fx(fr.dim, "reaper_smoke", c, { count: 8, radius: 0.8 });
        sound(player, "random.anvil_land", c, 0.5, 0.7);
        shake(player, c, 10, 0.2, 0.2);
    });
    after(13, () => {
        if (s.phantom?.entity && valid(s.phantom.entity)) safe(() => s.phantom.entity.remove());
        const spot = phantomSpot(player);
        const e = safe(() => player.dimension.spawnEntity("idex:reaper_phantom", spot.loc));
        if (!e) return;
        safe(() => e.setProperty("idex:size", 2.2));
        safe(() => e.teleport(spot.loc, { rotation: { x: 0, y: spot.yaw } }));
        cmd(e, "playanimation @s animation.idex.phantom.appear a 0.1");
        s.phantom = { entity: e, until: now() + 8 * 20, leaving: false };
        sound(player, "mob.wither.ambient", spot.loc, 0.5, 0.6);
        fx(fr.dim, "reaper_rune", spot.loc, { count: 10, radius: 1.5, rise: 0.6 });
    });
}
function phantomTick(player, s, t) {
    const ph = s.phantom;
    if (!ph) return;
    if (!valid(ph.entity)) {
        s.phantom = null;
        return;
    }
    const spot = phantomSpot(player);
    if (ph.entity.dimension.id !== player.dimension.id) {
        safe(() => ph.entity.remove());
        s.phantom = null;
        return;
    }
    safe(() => ph.entity.teleport(spot.loc, { rotation: { x: 0, y: spot.yaw } }));
    if (t % 4 === 0) fx(player.dimension, "reaper_mist", add(spot.loc, { x: 0, y: 1.5, z: 0 }), { count: 1, radius: 0.6 });
    if (t % 9 === 0) fx(player.dimension, "reaper_rune", add(spot.loc, { x: 0, y: 2, z: 0 }), { count: 1, radius: 1.4, rise: 0.5 });
    if (!ph.leaving && t >= ph.until) {
        ph.leaving = true;
        cmd(ph.entity, "playanimation @s animation.idex.phantom.vanish a 0.1");
        fx(player.dimension, "reaper_smoke", add(spot.loc, { x: 0, y: 2, z: 0 }), { count: 12, radius: 1.5 });
        const e = ph.entity;
        after(16, () => {
            if (valid(e)) e.remove();
            if (s.phantom?.entity === e) s.phantom = null;
        });
    }
}

// ------------------------------------------------------------------ 4. Blood Moon
function castBloodMoon(player, s) {
    const fr = frame(player);
    play(player, "blood_moon", 40);
    trail(player, fr, "blood_moon", { size: 0.2, life: 0.45 });
    sound(player, "mob.evocation_illager.prepare_attack", null, 0.6, 0.9);
    [10, 18, 26].forEach((tk, i) => {
        after(tk, () => {
            const f = liveFrame(player, fr);
            fx(f.dim, "reaper_circle_face", local(f, [0, 3.9, 0.6]), { size: 1.6 + i * 1.8, life: 1.0 + (2 - i) * 0.2, spin: 120 - i * 50 });
            fx(f.dim, "reaper_sparks", local(f, [0, 3.9, 0.6]), { count: 8 });
        });
    });
    after(32, () => {
        const center = { ...player.location };
        const moon = local(frame(player), [0, 9, -9]);
        fx(fr.dim, "reaper_moon", moon, { size: 10, life: 12 });
        fx(fr.dim, "reaper_circle_face", moon, { size: 13, life: 1.4, spin: 30 });
        sound(player, "ambient.weather.thunder", center, 0.5, 0.7);
        sound(player, "mob.enderdragon.growl", center, 0.5, 0.5);
        const tag = `idex_bm_${player.id}`;
        cmd(player, `fog @a[x=${center.x.toFixed(1)},y=${center.y.toFixed(1)},z=${center.z.toFixed(1)},r=28] push idex:blood_moon_fog ${tag}`);
        after(12 * 20, () => cmd(player, `fog @a remove ${tag}`));
        s.bloodMoonUntil = now() + 12 * 20;
        cmd(player, "effect @s strength 12 1 true");
        for (let k = 0; k < 24; k++) {
            after(k * 10, () => {
                fx(fr.dim, "reaper_mist", center, { count: 4, radius: 9 });
                fx(fr.dim, "reaper_rune", add(center, { x: 0, y: 1, z: 0 }), { count: 3, radius: 8, rise: 0.4 });
                fx(fr.dim, "reaper_mini_crescent", add(center, { x: 0, y: 1.5, z: 0 }), { count: 3, radius: 8 });
                fx(fr.dim, "reaper_aura", center, { count: 4, radius: 8, rise: 0.6 });
            });
        }
    });
}
function bloodMoonTick(player, s, t) {
    if (s.bloodMoonUntil <= t) return;
    if (t % 3 === 0) {
        fx(player.dimension, "reaper_aura", player.location, { count: 3, radius: 0.55 });
        fx(player.dimension, "reaper_trail_dark", add(player.location, { x: (Math.random() - 0.5) * 0.8, y: 0.4, z: (Math.random() - 0.5) * 0.8 }), { life: 0.6, size: 0.35 });
    }
}

// ------------------------------------------------------------------ 5. Abyssal Reap
function castAbyssalReap(player) {
    const fr = frame(player);
    play(player, "abyssal_reap", 80);
    trail(player, fr, "abyssal_reap", { smoke: true });
    sound(player, "item.trident.riptide_3", null, 0.5, 0.8);
    let center;
    // phase 1: slam -> layered circle, rings turning against each other
    after(35, () => {
        center = { ...player.location };
        fx(fr.dim, "reaper_circle", center, { size: 14, life: 4.2, spin: 22 });
        fx(fr.dim, "reaper_circle_ring_a", center, { size: 15.5, life: 4.2, spin: -40 });
        fx(fr.dim, "reaper_circle_ring_b", center, { size: 9, life: 4.2, spin: 65 });
        fx(fr.dim, "reaper_void_wave", center, { size: 6, life: 0.5 });
        fx(fr.dim, "reaper_smoke", center, { count: 10, radius: 0.8 });
        sound(player, "random.anvil_land", center, 0.4, 0.9);
        sound(player, "mob.evocation_illager.cast_spell", center, 0.5, 1);
        shake(player, center, 14, 0.3, 0.3);
        mimic(player, "abyssal_reap");
    });
    // phase 2: cracks with red light, black smoke rising, slowness inside
    after(44, () => {
        const cracks = [];
        for (let i = 0; i < 11; i++) {
            const a = Math.random() * Math.PI * 2;
            const r = 1 + Math.random() * 5.5;
            const p = { x: center.x + Math.cos(a) * r, y: center.y, z: center.z + Math.sin(a) * r };
            cracks.push(p);
            after(i, () => fx(fr.dim, "reaper_crack", p, { size: 2.2 + Math.random() * 1.6, life: 3.6 - i * 0.05 }));
        }
        for (let k = 0; k < 6; k++) {
            after(k * 5, () => {
                for (const p of cracks) {
                    if (Math.random() < 0.5) fx(fr.dim, "reaper_smoke", add(p, { x: 0, y: 0.3, z: 0 }), { count: 2, radius: 0.3, size: 0.6 });
                }
                fx(fr.dim, "reaper_energy_rise", center, { count: 6, radius: 6.5 });
            });
        }
        for (const e of enemies(player, center, 7.5)) cmd(e, "effect @s slowness 3 2 true");
        sound(player, "mob.warden.dig", center, 0.7, 0.8);
    });
    // phase 3: giant shadow blade above the circle, slam -> Black Void Impact
    let giant;
    after(52, () => {
        giant = safe(() => fr.dim.spawnEntity("idex:reaper_phantom", add(center, { x: 0, y: 7, z: 0 })));
        if (!giant) return;
        safe(() => giant.setProperty("idex:size", 3.6));
        safe(() => giant.teleport(add(center, { x: 0, y: 7, z: 0 }), { rotation: { x: 0, y: fr.yaw + 90 } }));
        cmd(giant, "playanimation @s animation.idex.phantom.hang a 0.1");
        fx(fr.dim, "reaper_rune", add(center, { x: 0, y: 6, z: 0 }), { count: 12, radius: 3, rise: 0.2 });
        sound(player, "mob.wither.spawn", center, 0.6, 0.5);
    });
    after(68, () => valid(giant) && cmd(giant, "playanimation @s animation.idex.phantom.fall a 0.05"));
    after(74, () => {
        fx(fr.dim, "reaper_void_wave", center, { size: 17, life: 0.9 });
        after(3, () => fx(fr.dim, "reaper_void_wave", center, { size: 11, life: 0.7 }));
        fx(fr.dim, "reaper_void_burst", center, { count: 60, speed: 1.2, size: 1.1 });
        fx(fr.dim, "reaper_sparks", add(center, { x: 0, y: 0.5, z: 0 }), { count: 30, speed: 1.6 });
        fx(fr.dim, "reaper_smoke", center, { count: 16, radius: 2.5, size: 1.2 });
        for (const e of enemies(player, center, 7.5)) hurt(player, e, 20, { from: center, h: 1.3, v: 0.65 });
        shake(player, center, 24, 0.6, 0.5);
        sound(player, "random.explode", center, 0.6, 1);
        sound(player, "mob.warden.sonic_boom", center, 0.6, 0.8);
    });
    after(82, () => valid(giant) && giant.remove());
}

// ------------------------------------------------------------------ 6. Eclipse Requiem (ultimate)
function castEclipseRequiem(player) {
    const fr = frame(player);
    play(player, "eclipse_requiem", CLIP_TICKS.eclipse_requiem);
    const dim = fr.dim;
    // Phase 1 - Awakening: red lines light up shaft -> joints -> blade
    sound(player, "portal.trigger", null, 0.6, 0.7);
    GLOW.forEach((p, i) => {
        after(4 + Math.floor((i / GLOW.length) * 26), () => {
            const at = local(liveFrame(player, fr), p);
            fx(dim, "reaper_trail", at, { size: 0.14, life: 0.9 });
            if (i % 6 === 0) fx(dim, "reaper_sparks", at, { count: 3, speed: 0.4 });
        });
    });
    [6, 14, 22, 30].forEach((tk, i) => after(tk, () => sound(player, "block.beacon.ambient", null, 0.6 + i * 0.25, 0.7 + i * 0.1)));
    // Phase 2 - Eclipse: black circle with a red ring becomes a black-red eclipse
    let sky;
    after(34, () => {
        sky = local(frame(player), [0, 15, 5]);
        fx(dim, "reaper_eclipse_disc", sky, { size: 11, life: 5.6 });
        fx(dim, "reaper_ring", sky, { size: 1, life: 0.1 });
        const tag = `idex_ec_${player.id}`;
        const c = player.location;
        cmd(player, `fog @a[x=${c.x.toFixed(1)},y=${c.y.toFixed(1)},z=${c.z.toFixed(1)},r=34] push idex:eclipse_fog ${tag}`);
        after(9 * 20, () => cmd(player, `fog @a remove ${tag}`));
        sound(player, "ambient.weather.thunder", c, 0.4, 0.8);
    });
    after(46, () => {
        fx(dim, "reaper_eclipse_corona", sky, { size: 11.5, life: 4.4 });
        fx(dim, "reaper_circle_face", sky, { size: 14, life: 1.2, spin: 20 });
        sound(player, "mob.enderdragon.growl", player.location, 0.4, 0.6);
    });
    // Phase 3 - Reaper Domain + ring of phantom scythes
    let center;
    const phantoms = [];
    after(60, () => {
        center = { ...player.location };
        fx(dim, "reaper_circle", center, { size: 21, life: 5.0, spin: 12 });
        fx(dim, "reaper_circle_ring_a", center, { size: 23, life: 5.0, spin: -20 });
        fx(dim, "reaper_circle_ring_b", center, { size: 13, life: 5.0, spin: 35 });
        sound(player, "mob.evocation_illager.cast_spell", center, 0.4, 1);
        for (let k = 0; k < 12; k++) {
            after(k * 4, () => {
                fx(dim, "reaper_rune", add(center, { x: 0, y: 0.5, z: 0 }), { count: 3, radius: 9, rise: 0.5 });
                fx(dim, "reaper_mini_crescent", add(center, { x: 0, y: 1, z: 0 }), { count: 2, radius: 9 });
                fx(dim, "reaper_mist", center, { count: 2, radius: 9 });
                fx(dim, "reaper_energy_rise", center, { count: 6, radius: 9 });
            });
        }
    });
    after(70, () => {
        for (let i = 0; i < 6; i++) {
            const a = (i / 6) * Math.PI * 2;
            const p = { x: center.x + Math.cos(a) * 5, y: center.y + 4.5, z: center.z + Math.sin(a) * 5 };
            after(i * 2, () => {
                const e = safe(() => dim.spawnEntity("idex:reaper_phantom", p));
                if (!e) return;
                safe(() => e.setProperty("idex:size", 1.4));
                const yaw = (Math.atan2(-(center.x - p.x), center.z - p.z) * 180) / Math.PI;
                safe(() => e.teleport(p, { rotation: { x: 0, y: yaw } }));
                cmd(e, "playanimation @s animation.idex.phantom.hang a 0.1");
                fx(dim, "reaper_smoke", p, { count: 6, radius: 0.6 });
                phantoms.push(e);
            });
        }
        sound(player, "mob.wither.ambient", center, 0.5, 0.8);
    });
    // Phase 4 - Requiem: spin, stop, every phantom falls
    trail(player, fr, "eclipse_requiem", { smoke: true, size: 0.2 });
    after(91, () => sound(player, "item.trident.riptide_3", null, 0.6, 1));
    after(104, () => phantoms.forEach((e) => valid(e) && cmd(e, "playanimation @s animation.idex.phantom.fall a 0.05")));
    after(108, () => {
        fx(dim, "reaper_beam", center, { count: 40, radius: 9 });
        for (const e of phantoms) {
            if (!valid(e)) continue;
            const g = { x: e.location.x, y: center.y, z: e.location.z };
            fx(dim, "reaper_void_wave", g, { size: 4.5, life: 0.6 });
            fx(dim, "reaper_sparks", add(g, { x: 0, y: 0.4, z: 0 }), { count: 14 });
        }
        for (const e of enemies(player, center, 10)) hurt(player, e, 15, { from: center, h: 0.6, v: 0.5 });
        shake(player, center, 30, 0.5, 0.45);
        sound(player, "random.explode", center, 0.5, 1);
    });
    after(114, () => phantoms.forEach((e) => valid(e) && e.remove()));
    // (silence 114 - 117)
    // Phase 5 - Final Crescent: drag along the ground, flick up, giant 3-layer crescent
    after(117, () => sound(player, "item.trident.riptide_1", null, 0.5, 0.8));
    after(131, () => {
        const f = liveFrame(player, fr);
        const dir = f.f;
        const o = local(f, [0, 0.9, 1.6]);
        sound(player, "mob.wither.shoot", o, 0.4, 1);
        sound(player, "mob.warden.sonic_boom", o, 0.8, 0.8);
        shake(player, o, 20, 0.35, 0.35);
        launchCrescent(player, o, dir, { size: 3.4, variant: 1, dmg: 28, range: 32, speed: 1.25, radius: 3.4 });
        after(2, () => launchCrescent(player, add(o, { x: 0, y: 0.1, z: 0 }), dir, { size: 2.8, variant: 2, dmg: 0, range: 30, speed: 1.27, radius: 3, lift: 0.02 }));
        after(4, () => launchCrescent(player, add(o, { x: 0, y: 0.2, z: 0 }), dir, { size: 2.2, variant: 3, dmg: 0, range: 28, speed: 1.3, radius: 2.4, lift: 0.04 }));
    });
}

// ------------------------------------------------------------------ per-tick upkeep
system.runInterval(() => {
    const t = now();
    for (const player of world.getAllPlayers()) {
        safe(() => {
            const s = S(player);
            const h = holding(player);
            if (h && !s.holding) {
                hold(player);
                hud(player, true);
                tagLore(player);
            }
            s.holding = h;
            if (h && t >= s.busyUntil && t >= (s.animEnd ?? 0) && t - s.lastHold > 60) hold(player);
            if (h && t % 10 === 0) hud(player, false);
            phantomTick(player, s, t);
            bloodMoonTick(player, s, t);
        });
    }
}, 1);

function tagLore(player) {
    const eq = player.getComponent("equippable");
    const item = eq?.getEquipment("Mainhand");
    if (!item || item.typeId !== ITEM) return;
    const cur = item.getLore();
    if (cur.length === LORE.length && cur.every((l, i) => l === LORE[i])) return;
    item.setLore(LORE);
    eq.setEquipment("Mainhand", item);
}
